services:
    postgres:
        image: 'postgres:18'
        container_name: 'pizzeria-pg'
        restart: always
        environment:
            POSTGRES_USER: pizzeria
            POSTGRES_PASSWORD: pizzeria14256
            POSTGRES_DB: pizzeria
            PGDATA: /var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - ./pg-data:/var/lib/postgresql/data/pgdata

volumes:
    pg-data:
        driver: local